# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_user_birth_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('tasks', models.CharField(max_length=255)),
            ],
        ),
    ]
