# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='tasks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='appointments.User'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
