# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_wishlist', '0002_auto_20180426_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('item_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_item', to='my_wishlist.User')),
            ],
        ),
    ]
